waterPipelines = [
	"28Th Street",
	"30Th Street",
	"Aero Drive",
	"Alvarado 1st",
	"Alvarado 2nd",
	"Balboa Avenue",
	"Balboa Park",
	"Bernardo Center Drive",
	"Bonita",
	"Cabrillo Palisades",
	"Camino Ruiz",
	"Carmel Country",
	"Carmel Creek",
	"Carmel Mountain",
	"Carmel Valley",
	"Catalina",
	"Clairemont Mesa Crosstie",
	"College Ranch Feeder",
	"Commercial Street",
	"Coronado",
	"Del Mar Heights",
	"Dulzura Conduit",
	"El Camino Real",
	"El Capitan",
	"El Monte",
	"Electric Avenue",
	"Elliot",
	"Encanto Park",
	"Green Valley",
	"Harbor Drive 1st",
	"Harbor Drive 2nd",
	"Jogging Trail",
	"Kearny Mesa",
	"La Jolla Shores",
	"Laurel Street",
	"Linda Vista",
	"Lomica",
	"Mercy",
	"Mid-City",
	"Miramar",
	"Miramar 2A",
	"Miramar Cross",
	"Miramar Extension",
	"Miramar Road",
	"Montgomery",
	"Morena",
	"Murray 1st",
	"Murray 2nd",
	"North Torrey Pines",
	"Ocean View Hills",
	"Olivenhain Mwd",
	"Otay 1st",
	"Otay 2nd",
	"Otay 3rd",
	"Otay Mesa",
	"Otay Mesa-Bonita Connection",
	"Pacific Beach",
	"Pacific Highway",
	"Paradise Mesa",
	"Paradise Mesa Cross",
	"Penasquitos",
	"Pershing Street",
	"Point Loma Feeder",
	"Pomerado",
	"Pomerado 2nd",
	"Ramona Feeder",
	"Rancho Bernardo",
	"Rancho Bernardo No 2",
	"Redwood Village",
	"San Vicente 1st",
	"San Vicente 2nd",
	"San Vicente Aqueduct Connection",
	"San Ysidro",
	"Scripps Ranch",
	"Shepherd Canyon",
	"Soledad Road",
	"Soledad Valley",
	"Sorrento Road",
	"Sorrento Valley",
	"South San Diego No 1",
	"South San Diego No 2",
	"Sutherland",
	"Texas Street",
	"Thorn Street",
	"Trojan",
	"University Avenue",
	"Upas Street",
	"Via De La Valle",
]